bundle:
	browserify Compiler/parser.js Compiler/abstractSyntaxTree.js Compiler/intermediateCodeGenerator.js Compiler/xmlbuilder.js Compiler/compiler.js app.js -o bundle.js
prod:
	browserify Compiler/parser.js Compiler/abstractSyntaxTree.js Compiler/intermediateCodeGenerator.js Compiler/xmlbuilder.js Compiler/compiler.js production.js -o bundle.js